// source: https://calendar.google.com/calendar/u/0/flairdata
export default [
  [
    "flairdataaction.rsr",
    [
      [
        "babyshower",
        [
          [2, "babyshower"],
          [2, "maternity"],
          [2, "baby shower"],
        ],
      ],
      [
        "bookclub",
        [
          [2, "book club"],
          [2, "reading"],
        ],
      ],
      [
        "datenight",
        [
          [3, "date night"],
          [3, "datenight"],
          [3, "candlelight dinner"],
          [3, "candle light dinner"],
          [3, "romantic dinner"],
        ],
      ],
      ["thanksgiving", [[2, "thanksgiving"]]],
      [
        "drinks",
        [
          [2, "cocktail"],
          [2, "drinks"],
          [2, "cocktails"],
          [2, "Stag night"],
          [2, "Hen night"],
          [2, "Bachelorette Party"],
          [2, "stag party"],
          [2, "Stag do"],
          [2, "Hen do"],
          [2, "Stag and Doe"],
          [2, "Ladies night"],
          [2, "wine night"],
          [2, "wine bar"],
        ],
      ],
      [
        "cooking",
        [
          [3, "cooking"],
          [3, "cook dinner"],
          [3, "cook lunch"],
          [3, "cook meal"],
          [3, "prepare meal"],
          [3, "prepare dinner"],
          [3, "prepare lunch"],
          [3, "make dinner"],
          [3, "make lunch"],
        ],
      ],
      [
        "xmas",
        [
          [3, "christmas"],
          [3, "xmas"],
          [3, "x-mas"],
          [3, "Boxing Day"],
        ],
      ],
      ["quinceanera", [[2, "quinceanera"]]],
      [
        "walk",
        [
          [2, "going for a walk"],
          [2, "walking"],
        ],
      ],
      [
        "learnlanguage",
        [
          [2, "French Course"],
          [2, "German Course"],
          [2, "English Course"],
          [2, "Italian Course"],
          [2, "Chinese Course"],
          [2, "Japanese Course"],
          [2, "Korean Course"],
          [2, "Polish Course"],
          [2, "Spanish Course"],
          [2, "Arabic Course"],
          [2, "Hebrew Course"],
          [2, "Portuguese Course"],
          [2, "Thai Course"],
          [2, "Russian Course"],
          [2, "Turkish Course"],
          [2, "Dutch Course"],
          [2, "Bulgarian Course"],
          [2, "Greek Course"],
          [2, "Hindi Course"],
          [2, "Indonesian Course"],
          [2, "Vietnamese Course"],
          [2, "Norwegian Course"],
          [2, "Swedish Course"],
          [2, "Slovenian Course"],
          [2, "Ukranian Course"],
          [2, "Slovak Course"],
          [2, "Lithuanian Course"],
          [2, "Latvian Course"],
          [2, "Hungarian Course"],
          [2, "Finnish Course"],
          [2, "Filipino Course"],
          [2, "Farsi Course"],
          [2, "Danish Course"],
          [2, "Czech Course"],
          [2, "Croatian Course"],
          [2, "Catalan Course"],
          [2, "French Class"],
          [2, "German Class"],
          [2, "English Class"],
          [2, "Italian Class"],
          [2, "Chinese Class"],
          [2, "Japanese Class"],
          [2, "Korean Class"],
          [2, "Polish Class"],
          [2, "Spanish Class"],
          [2, "Arabic Class"],
          [2, "Hebrew Class"],
          [2, "Portuguese Class"],
          [2, "Thai Class"],
          [2, "Russian Class"],
          [2, "Turkish Class"],
          [2, "Dutch Class"],
          [2, "Bulgarian Class"],
          [2, "Greek Class"],
          [2, "Hindi Class"],
          [2, "Indonesian Class"],
          [2, "Vietnamese Class"],
          [2, "Norwegian Class"],
          [2, "Swedish Class"],
          [2, "Slovenian Class"],
          [2, "Ukranian Class"],
          [2, "Slovak Class"],
          [2, "Lithuanian Class"],
          [2, "Latvian Class"],
          [2, "Hungarian Class"],
          [2, "Finnish Class"],
          [2, "Filipino Class"],
          [2, "Farsi Class"],
          [2, "Danish Class"],
          [2, "Czech Class"],
          [2, "Croatian Class"],
          [2, "Catalan Class"],
          [2, "Practice French"],
          [2, "Practice German"],
          [2, "Practice English"],
          [2, "Practice Italian"],
          [2, "Practice Chinese"],
          [2, "Practice Japanese"],
          [2, "Practice Korean"],
          [2, "Practice Polish"],
          [2, "Practice Spanish"],
          [2, "Practice Arabic"],
          [2, "Practice Hebrew"],
          [2, "Practice Portuguese"],
          [2, "Practice Thai"],
          [2, "Practice Russian"],
          [2, "Practice Turkish"],
          [2, "Practice Dutch"],
          [2, "Practice Bulgarian"],
          [2, "Practice Greek"],
          [2, "Practice Hindi"],
          [2, "Practice Indonesian"],
          [2, "Practice Vietnamese"],
          [2, "Practice Norwegian"],
          [2, "Practice Swedish"],
          [2, "Practice Slovenian"],
          [2, "Practice Ukranian"],
          [2, "Practice Slovak"],
          [2, "Practice Lithuanian"],
          [2, "Practice Latvian"],
          [2, "Practice Hungarian"],
          [2, "Practice Finnish"],
          [2, "Practice Filipino"],
          [2, "Practice Farsi"],
          [2, "Practice Danish"],
          [2, "Practice Czech"],
          [2, "Practice Croatian"],
          [2, "Practice Catalan"],
        ],
      ],
      [
        "reachout",
        [
          [2, "reach out to"],
          [2, "write letter"],
          [2, "send invitations"],
        ],
      ],
      [
        "videogaming",
        [
          [2, "Videogames"],
          [2, "Videogaming"],
          [2, "video games"],
          [2, "video game"],
          [2, "video gaming"],
          [3, "AGDQ"],
          [3, "SGDQ"],
          [3, "Games Done Quick"],
        ],
      ],
      [
        "walkingdog",
        [
          [2, "walk the dog"],
          [2, "dogsitting"],
          [2, "dog sitting"],
          [2, "walk dog"],
          [2, "dog walking"],
          [2, "dog walker"],
          [2, "take dog out"],
          [2, "take out dog"],
          [2, "dog walk"],
          [2, "walking puppy"],
          [2, "puppy walk"],
        ],
      ],
      ["basketball", [[2, "basketball"]]],
      [
        "sleep",
        [
          [2, "sleeping"],
          [2, "resting"],
          [2, "relaxing"],
          [2, "napping"],
          [2, "sleep"],
          [2, "nap"],
        ],
      ],
      [
        "climbing",
        [
          [2, "climbing"],
          [2, "bouldering"],
        ],
      ],
      [
        "birthday",
        [
          [3, "bday"],
          [3, "birthday"],
          [3, "b-day"],
          [3, "b'day"],
        ],
      ],
      [
        "dinner ",
        [
          [2, "dinner "],
          [2, "dinners "],
          [2, "restaurant "],
          [2, "restaurants "],
          [2, "Family meal"],
        ],
      ],
      ["archery ", [[2, "archery"]]],
      ["soccer ", [[2, "soccer"]]],
      [
        "gym ",
        [
          [2, "gym "],
          [2, "workout "],
          [2, "workouts "],
          [2, "fitness program "],
          [2, "fitness class "],
          [2, "fitness test "],
          [2, "fitness evaluation "],
          [2, "fitness center "],
          [2, "fitness training "],
          [2, "weightlifting "],
          [2, "weight lifting "],
          [2, "crossfit"],
        ],
      ],
      [
        "hiking ",
        [
          [2, "hiking "],
          [2, "hike "],
          [2, "hikes"],
        ],
      ],
      [
        "coffee ",
        [
          [2, "coffee "],
          [2, "coffees"],
        ],
      ],
      [
        "code ",
        [
          [2, "learn to code "],
          [2, "coding time "],
          [2, "hackathon "],
          [2, "Rails Girls "],
          [2, "Railsgirls "],
          [2, "Hour of Code "],
          [2, "Codecademy "],
          [2, "Computer Science "],
          [2, "Programming in Python "],
          [2, "Web Programming "],
          [2, "Programming in Java "],
          [2, "Web Development"],
        ],
      ],
      [
        "dentist ",
        [
          [2, "dentist "],
          [2, "dentistry "],
          [2, "dental "],
          [3, "teeth cleaning"],
        ],
      ],
      ["triathlon ", [[2, "triathlon"]]],
      [
        "islamicnewyear ",
        [
          [4, "Islamic New Year "],
          [4, "Hijri New Year "],
          [4, "Parsi New Year"],
        ],
      ],
      [
        "pride ",
        [
          [2, "dyke march "],
          [2, "christopher street day "],
          [2, "gay parade "],
          [2, "gay pride "],
          [2, "gayglers "],
          [2, "gaygler "],
          [2, "lesbian march "],
          [2, "lesbian parade "],
          [2, "lesbian pride "],
          [2, "euro pride "],
          [2, "europride "],
          [2, "world pride "],
          [2, "worldpride "],
          [2, "Gay\u0026 lesbian "],
          [2, "gay lesbian "],
          [2, "gay and lesbian"],
        ],
      ],
      [
        "read ",
        [
          [2, "reading "],
          [2, "newspaper "],
          [2, "ebook"],
        ],
      ],
      [
        "gamenight ",
        [
          [2, "boardgames "],
          [2, "boardgame "],
          [2, "board games "],
          [2, "board game"],
        ],
      ],
      ["handball ", [[2, "Handball"]]],
      [
        "pingpong ",
        [
          [2, "ping pong "],
          [4, "table tennis "],
          [2, "ping-pong "],
          [2, "pingpong"],
        ],
      ],
      ["wrestling ", [[2, "Wrestling"]]],
      [
        "chinesenewyear ",
        [
          [4, "chinese new year "],
          [4, "chinese new years "],
          [4, "chinese new year 's"],
          [4, "Vietnamese New Year"],
          [4, "Tết"],
          [4, "Chinese New Year"],
          [4, "Chinese Lunar New Year"],
        ],
      ],
      [
        "rowing",
        [
          [2, "Rowing"],
          [2, "Head of the Charles"],
          [2, "May Bumps"],
          [2, "Head of the River Race"],
        ],
      ],
      [
        "athleticsthrowing",
        [
          [2, "shot put"],
          [2, "discus"],
          [2, "javelin"],
          [2, "hammer throw"],
        ],
      ],
      [
        "saintpatricksday",
        [
          [2, "St Patricks"],
          [2, "St Patrick's"],
        ],
      ],
      [
        "cycling ",
        [
          [2, "bicycle "],
          [2, "cycling "],
          [2, "bike "],
          [2, "bicycles "],
          [2, "bikes "],
          [2, "Biking "],
          [2, "Mountain Biking "],
          [2, "Mountain Bike"],
        ],
      ],
      [
        "halloween ",
        [
          [2, "halloween "],
          [2, "helloween "],
          [2, "hallowe 'en"],
          [2, "Allhalloween"],
          [2, "All Hallows'Eve "],
          [2, "All Saints ' Eve"],
        ],
      ],
      ["baseball", [[2, "baseball"]]],
      [
        "cinema",
        [
          [2, "movie"],
          [2, "cinema"],
          [2, "movies"],
        ],
      ],
      [
        "concert",
        [
          [2, "concert"],
          [2, "gig"],
          [2, "concerts"],
          [2, "gigs"],
        ],
      ],
      ["athleticsjumping", [[2, "Jumping"]]],
      [
        "xmasparty",
        [
          [4, "christmas party"],
          [4, "xmas party"],
          [4, "x-mas party"],
          [4, "christmas eve party"],
          [4, "xmas eve party"],
          [4, "x-mas eve party"],
        ],
      ],
      [
        "planmyday",
        [
          [2, "plan week"],
          [2, "plan quarter"],
          [2, "plan day"],
          [2, "plan vacation"],
          [2, "week planning"],
          [2, "vacation planning"],
        ],
      ],
      ["cyclingbmx", [[2, "BMX"]]],
      [
        "art",
        [
          [2, "painting"],
          [2, "art workshop"],
          [2, "art workshops"],
          [2, "sketching workshop"],
          [2, "drawing workshop"],
        ],
      ],
      ["camping", [[2, "camping"]]],
      [
        "dancing",
        [
          [2, "dance"],
          [2, "dancing"],
          [2, "dances"],
          [2, "ballet"],
        ],
      ],
      [
        "clean",
        [
          [2, "clean the house"],
          [2, "clean the apartment"],
          [2, "clean house"],
          [2, "tidy up"],
          [2, "vacuum clean"],
          [2, "vacuum cleaning"],
        ],
      ],
      [
        "xmasmeal",
        [
          [5, "christmas dinner"],
          [5, "christmas lunch"],
          [5, "christmas brunch"],
          [5, "christmas luncheon"],
          [5, "xmas dinner"],
          [5, "xmas lunch"],
          [5, "xmas brunch"],
          [5, "xmas luncheon"],
          [5, "x-mas dinner"],
          [5, "x-mas lunch"],
          [5, "x-mas brunch"],
          [5, "x-mas luncheon"],
          [5, "christmas eve dinner"],
          [5, "christmas eve lunch"],
          [5, "christmas eve brunch"],
          [5, "christmas eve luncheon"],
          [5, "xmas eve dinner"],
          [5, "xmas eve lunch"],
          [5, "xmas eve brunch"],
          [5, "xmas eve luncheon"],
          [5, "x-mas eve dinner"],
          [5, "x-mas eve lunch"],
          [5, "x-mas eve brunch"],
          [5, "x-mas eve luncheon"],
        ],
      ],
      [
        "shooting",
        [
          [2, "shooting sport"],
          [2, "shooting sports"],
          [2, "shooting competition"],
          [2, "competitive shooting"],
        ],
      ],
      ["graduation", [[2, "graduation"]]],
      [
        "oilchange",
        [
          [2, "oil change"],
          [2, "car service"],
        ],
      ],
      ["boxing", [[2, "Boxing"]]],
      [
        "cricket",
        [
          [2, "cricket game"],
          [2, "cricket match"],
          [2, "cricket competition"],
        ],
      ],
      [
        "carmaintenance",
        [
          [2, "car repair"],
          [2, "auto repair"],
          [2, "car maintenance"],
          [2, "auto maintenance"],
          [2, "car mechanic"],
          [2, "auto mechanic"],
          [2, "tire replacement"],
          [2, "tire change"],
        ],
      ],
      ["fieldhockey", [[2, "Field hockey"]]],
      ["billiard", [[2, "billiard"]]],
      [
        "genericnewyear",
        [
          [3, "New Year"],
          [3, "new year's "],
          [3, "new years"],
        ],
      ],
      [
        "running ",
        [
          [2, "jog "],
          [2, "jogging "],
          [2, "running "],
          [2, "jogs "],
          [2, "Track and field "],
          [2, "track\u0026 field "],
          [2, "sprinting"],
        ],
      ],
      [
        "handcraft ",
        [
          [2, "handicraft "],
          [2, "crochet "],
          [2, "knitting "],
          [2, "patchwork "],
          [2, "embroidery "],
          [2, "quilting "],
          [2, "sewing "],
          [2, "felting "],
          [2, "millinery"],
        ],
      ],
      [
        "repair ",
        [
          [2, "fridge repair "],
          [2, "handyman "],
          [2, "electrician "],
          [2, "plumber "],
          [2, "DIY"],
        ],
      ],
      [
        "backtoschool ",
        [
          [2, "backtoschool "],
          [2, "back to school "],
          [2, "first school day "],
          [2, "first day of school "],
          [2, "back2school "],
          [2, "back 2 school"],
        ],
      ],
      [
        "equestrian ",
        [
          [2, "Equestrian "],
          [2, "Dressage "],
          [2, "Eventing "],
          [2, "Horse riding "],
          [2, "Horseriding"],
        ],
      ],
      [
        "kayaking ",
        [
          [2, "kayaking "],
          [2, "Canoeing "],
          [2, "Canoe"],
        ],
      ],
      [
        "santa ",
        [
          [2, "Santa Claus "],
          [4, "Father Christmas"],
        ],
      ],
      [
        "wedding ",
        [
          [2, "wedding "],
          [2, "wedding eve "],
          [2, "wedding-eve party "],
          [2, "weddings"],
        ],
      ],
      ["fencing ", [[2, "Fencing"]]],
      [
        "violin2 ",
        [
          [2, "violin "],
          [2, "violins"],
        ],
      ],
      [
        "manicure ",
        [
          [2, "manicure "],
          [2, "pedicure "],
          [2, "manicures "],
          [2, "pedicures"],
        ],
      ],
      ["yoga ", [[2, "yoga"]]],
      [
        "massage ",
        [
          [2, "massage "],
          [2, "back rub "],
          [2, "backrub "],
          [2, "massages"],
        ],
      ],
      [
        "bbq ",
        [
          [2, "bbq "],
          [2, "barbecue "],
          [2, "barbeque"],
        ],
      ],
      [
        "americanfootball ",
        [
          [2, "American Football "],
          [2, "Superbowl "],
          [2, "Super Bowl "],
          [2, "Football"],
        ],
      ],
      [
        "theatreopera ",
        [
          [2, "opera "],
          [2, "theatre "],
          [2, "theater"],
        ],
      ],
      ["tennis ", [[2, "tennis"]]],
      [
        "sailing ",
        [
          [2, "sail "],
          [2, "sailing "],
          [2, "boat cruise "],
          [2, "sailboat"],
        ],
      ],
      [
        "skiing2 ",
        [
          [2, "skiing "],
          [2, "ski "],
          [2, "skis "],
          [2, "Snowboarding "],
          [2, "snowshoeing "],
          [2, "snow shoe "],
          [2, "snow boarding"],
        ],
      ],
      ["volleyball ", [[2, "Volleyball"]]],
      [
        "mardigras ",
        [
          [2, "Mardi Gras "],
          [2, "Mardigras "],
          [2, "Shrove Tuesday "],
          [2, "Fat Tuesday"],
        ],
      ],
      ["golf ", [[2, "golf"]]],
      [
        "breakfast ",
        [
          [2, "breakfast "],
          [2, "breakfasts "],
          [2, "brunch "],
          [2, "brunches"],
        ],
      ],
      [
        "haircut ",
        [
          [2, "haircut "],
          [2, "hairdresser "],
          [2, "hair"],
        ],
      ],
      [
        "lunch ",
        [
          [2, "lunch "],
          [2, "lunches "],
          [2, "luncheon"],
        ],
      ],
      [
        "nowruz ",
        [
          [4, "Persian New Year "],
          [4, "Nowruz"],
        ],
      ],
      ["artisticgymnastics ", [[2, "artistic gymnastics"]]],
      [
        "karate ",
        [
          [2, "karate "],
          [2, "judo "],
          [2, "taekwondo "],
          [2, "martial arts "],
          [2, "Jujutsu "],
          [2, "Aikido "],
          [2, "jiu-jitsu "],
          [2, "jiu jitsu"],
        ],
      ],
      [
        "learninstrument ",
        [
          [2, "piano "],
          [2, "singing "],
          [2, "music Class "],
          [2, "choir practice "],
          [2, "flute "],
          [2, "orchestra "],
          [2, "oboe "],
          [2, "clarinet "],
          [2, "saxophone "],
          [2, "cornett "],
          [2, "trumpet "],
          [2, "contrabass "],
          [2, "cello "],
          [2, "trombone "],
          [2, "tuba "],
          [2, "music ensemble "],
          [2, "string quartett "],
          [2, "guitar lesson "],
          [2, "classical music "],
          [2, "choir"],
        ],
      ],
      ["rhythmicgymnastics ", [[2, "rhythmic gymnastics"]]],
      ["bowling ", [[2, "bowling"]]],
      [
        "valentinesday ",
        [
          [2, "Valentines Day "],
          [2, "Valentine Day "],
          [2, "Valentine 's Day"],
        ],
      ],
      [
        "beer",
        [
          [2, "beer"],
          [2, "beers"],
          [2, "Oktoberfest"],
          [2, "October Fest"],
          [2, "Octoberfest"],
        ],
      ],
      ["badminton", [[2, "badminton"]]],
      [
        "waterpolo",
        [
          [2, "Water polo"],
          [2, "waterpolo"],
        ],
      ],
      ["rugbysevens", [[2, "Rugby"]]],
      [
        "swimming",
        [
          [2, "swim"],
          [2, "swimming"],
          [2, "swims"],
          [2, "Diving"],
          [2, "Synchronized Swimming"],
        ],
      ],
    ],
  ],
] as const;
